#!/usr/bin/env python
import argparse
import sys
import os

from geo2fastq.config import VERSION
from geo2fastq import Geo

description = """
geo2fastq v{0}
""".format(VERSION)

p = argparse.ArgumentParser(
                           description=description,
                           )
p.add_argument("term",
               help="GEO search term (accession)",
               metavar="TERM"
               )
p.add_argument("-d", "--download",
               dest="download",
               help="Download data from GEO. If this option is not specified, only show metadata.",
               action="store_true",
               default=False,
               )

args = p.parse_args()

download = args.download
search_term = args.term

for gse, info in Geo.search(search_term):
    print "{0}\t{1}".format(gse, info['title'])
    for gsm,title in info['samples'].items():
        print "  {0}\t{1}".format(gsm, title)
    
    if download:
        g = Geo(gse)
        g.download()
